packages:
  base: !include ../base.yaml
  button: !include ../button-simple.yaml
  i2s: !include ../i2s.yaml
  mic: !include ../mic.yaml
  speaker: !include ../speaker.yaml
  media_player: !include ../media-player.yaml
