substitutions:
  name: "laundry-room-tv-control"
  friendly_name: "Laundry Room TV Control"
  mac_address: !secret mac_address_laundry_room_tv_control
  ip_address: "10.2.2.10"

packages:
  common: !include ./common/base.yaml
  net_wifi: !include ./common/net/wifi.yaml
  device: !include ./common/device/m5stack-atom/profiles/echo.yaml
  voice: !include ./common/device/m5stack-atom/voice-assistant-ptt.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

api:
  encryption:
    key: !secret api_key_laundry_room_tv_control

ota:
  - platform: esphome
    password: !secret ota_password_laundry_room_tv_control

button:
  - platform: template
    name: "Power Toggle"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF

  - platform: template
    name: "Volume Up"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0E01F

  - platform: template
    name: "Volume Down"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0D02F

  - platform: template
    name: "Mute"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0F00F

  - platform: template
    name: "Source"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0807F

  - platform: template
    name: "Home"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E09E61

  - platform: template
    name: "OK"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E016E9

  - platform: template
    name: "Back"
    on_press:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E01AE5

binary_sensor:
  - id: !extend atom_button
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
